"""
Frequency-based automatic assignment — generation service.

This module owns ALL of the period math (financial year, quarters, weeks)
and the duplicate-prevention check. It does NOT duplicate any assignment-
creation or workflow logic — every generated Assignment is created by
calling the existing `_create_brsr_assignment` from views.py, so a
scheduled assignment is byte-for-byte the same kind of object a human
creates manually (same workflow start, same reviewer linking, same
QuestionResponse seeding, same Pre-Final-Approval lock check).

Submission frequency is now a MANDATORY field on every assignment
(BRSRAssignmentForm.data_collection_frequency is required=True). This
means every Assignment created anywhere in the system — manual or
scheduled — always has a real period identity (period_code), which is
what makes the duplicate-prevention check below actually work. There is
no more "one-off, no frequency" branch.

AssignmentSchedule --> [this module] --> Assignment --> Workflow --> QuestionResponse
"""
import logging
from calendar import month_abbr
from datetime import date, timedelta
from django.utils import timezone
from .models import Assignment, AssignmentSchedule

logger = logging.getLogger(__name__)

MONTH_ABBR = {i: month_abbr[i].upper() for i in range(1, 13)}

# Calendar month a given quarter STARTS in (BRSR / Indian FY quarters).
QUARTER_START_MONTHS = {'Q1': 4, 'Q2': 7, 'Q3': 10, 'Q4': 1}


# ---------------------------------------------------------------------------
# Period math
# ---------------------------------------------------------------------------

def financial_year_for_date(d: date) -> str:
    """BRSR financial year runs April -> March, e.g. 2026-2027."""
    if d.month >= 4:
        return f"{d.year}-{d.year + 1}"
    return f"{d.year - 1}-{d.year}"


def quarter_for_date(d: date) -> str:
    if d.month in (4, 5, 6):
        return 'Q1'
    if d.month in (7, 8, 9):
        return 'Q2'
    if d.month in (10, 11, 12):
        return 'Q3'
    return 'Q4'  # Jan-Mar


def quarter_start_date(quarter_code: str, today: date) -> date:
    """Resolve the calendar start date of `quarter_code` for the financial
    year that `today` currently sits in."""
    month = QUARTER_START_MONTHS[quarter_code]
    year = today.year
    if month == 1 and today.month >= 4:
        # Q4 (Jan) of the FY that started this calendar year falls next year.
        year += 1
    elif month != 1 and today.month < 4:
        # We're in Jan-Mar, so this FY's Q1/Q2/Q3 happened last calendar year.
        year -= 1
    return date(year, month, 1)


def week_period_code(d: date) -> str:
    return f"Week-{d.isocalendar()[1]}"


def current_period_for_frequency(frequency, today: date):
    """
    Resolve the (financial_year, period_code, period_label) for the period
    `today` currently falls in, given a frequency. Used only to generate the
    *immediate* assignment when a schedule is first configured — this is
    intentionally independent of selected_months/selected_quarters (those
    only gate which *future* periods get auto-generated by the daily task).
    """
    fy = financial_year_for_date(today)

    if frequency == 'weekly':
        code = week_period_code(today)
        return fy, code, code

    if frequency == 'monthly':
        code = MONTH_ABBR[today.month]
        return fy, code, code

    if frequency == 'quarterly':
        quarter_code = quarter_for_date(today)
        return fy, quarter_code, quarter_code

    if frequency == 'annually':
        return fy, 'ANNUAL', f"FY{fy}"

    return fy, '', ''


def _period_due_date(schedule: AssignmentSchedule, trigger_date: date):
    """Best-effort due date for the generated Assignment, based on the
    schedule's own configuration. Never required for generation to
    succeed — falls back to None (no due date) if it can't be computed."""
    due_period_days = getattr(schedule, "due_period_days", None)
    if due_period_days:
        return trigger_date + timedelta(days=int(due_period_days))
    if schedule.frequency == 'weekly' and schedule.weekly_end_day is not None and schedule.weekly_start_day is not None:
        delta_days = (schedule.weekly_end_day - schedule.weekly_start_day) % 7
        return trigger_date + timedelta(days=delta_days)
    if schedule.frequency == 'monthly':
        next_month = trigger_date.replace(day=28) + timedelta(days=4)
        return next_month - timedelta(days=next_month.day)
    if schedule.frequency == 'quarterly':
        return trigger_date + timedelta(days=89)
    return None


# ---------------------------------------------------------------------------
# Duplicate prevention
# ---------------------------------------------------------------------------

def assignment_exists_for_period(schedule: AssignmentSchedule, financial_year: str, period_code: str) -> bool:
    """
    True if an Assignment has already been generated for this exact
    (schedule, financial_year, period_code) combination. This is the
    application-level half of duplicate prevention; a partial unique
    constraint on Assignment enforces the same rule at the DB level.

    NOTE: this only works correctly because create_assignment_from_schedule
    (below) passes the real period_code into `cleaned_data` BEFORE calling
    _create_brsr_assignment, rather than setting it on the Assignment after
    the fact. If period_code isn't present at creation time, every
    Assignment row would compare with period_code=None here and this check
    would silently never fire, letting annual/monthly/quarterly assignments
    recreate endlessly for the same financial year — this was the original
    bug and this check depends on that fix staying in place.
    """
    return Assignment.objects.filter(
        schedule=schedule, financial_year=financial_year, period_code=period_code
    ).exists()


# ---------------------------------------------------------------------------
# Which periods are due today, for a given schedule
# ---------------------------------------------------------------------------

def due_periods_for_schedule(schedule, today: date):
    """
    Returns a list of (financial_year, period_code, period_label) tuples
    that are due to be generated *today* for `schedule`. Empty list means
    nothing to do today. Pure function over duck-typed schedule attributes
    (frequency, weekly_start_day, selected_months, selected_quarters,
    financial_year) so it's independently unit-testable without the ORM.
    """
    periods = []
    fy = financial_year_for_date(today)

    if schedule.frequency == 'weekly':
        if schedule.weekly_start_day is not None and today.weekday() == schedule.weekly_start_day:
            code = week_period_code(today)
            periods.append((fy, code, code))

    elif schedule.frequency == 'monthly':
        if today.day == 1 and today.month in (schedule.selected_months or []):
            code = MONTH_ABBR[today.month]
            periods.append((fy, code, code))

    elif schedule.frequency == 'quarterly':
        for quarter_code in (schedule.selected_quarters or []):
            if quarter_code not in QUARTER_START_MONTHS:
                continue
            if today == quarter_start_date(quarter_code, today):
                periods.append((fy, quarter_code, quarter_code))

    elif schedule.frequency == 'annually':
        target_fy = schedule.financial_year or fy
        periods.append((target_fy, 'ANNUAL', f"FY{target_fy}"))

    return periods


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def create_assignment_from_schedule(schedule: AssignmentSchedule, financial_year: str,
                                     period_code: str, period_label: str, trigger_date: date):
    """
    Turns one due (schedule, period) pair into a real Assignment, reusing
    the existing manual-assignment creation path so workflow start,
    reviewer linking, QuestionResponse seeding, and the Pre-Final-Approval
    lock check are identical to a manually created assignment. Returns
    None (no-op) if this period was already generated.

    period_code / period_label are passed INSIDE cleaned_data so that
    _create_brsr_assignment's own duplicate-guard (plant/section/principle/
    financial_year/period_code) sees the real period at creation time,
    not None. This is what actually stops the same financial year (or
    month/quarter/week) from being recreated on every run.
    """
    # Local import avoids a circular import between views.py <-> this module.
    from .views import _create_brsr_assignment

    if assignment_exists_for_period(schedule, financial_year, period_code):
        return None

    if schedule.created_by_id is None:
        logger.warning(
            "AssignmentSchedule %s has no created_by set; skipping generation "
            "for period %s (an assigner is required).", schedule.schedule_id, period_code,
        )
        return None

    cleaned_data = {
        "plant": schedule.plant,
        "financial_year": financial_year,
        "assignee": schedule.assignee,
        "reviewer": schedule.reviewer,
        "priority": schedule.priority,
        "notes": schedule.notes,
        "due_date": _period_due_date(schedule, trigger_date),
        "data_collection_frequency": schedule.frequency,
        "assigner": schedule.created_by,
        "period_code": period_code,
        "period_label": period_label,
    }

    assignment = _create_brsr_assignment(
        user=schedule.created_by,
        section=schedule.section,
        principle=schedule.principle,
        cleaned_data=cleaned_data,
        question_queryset=schedule.questions.all(),
        workflow_template_override=schedule.workflow_template,
    )
    assignment.schedule = schedule
    assignment.save(update_fields=["schedule", "updated_at"])
    return assignment


def run_daily_schedule_generation(today=None):
    """
    Entry point for the Celery Beat task (see tasks.py). Iterates every
    active AssignmentSchedule, works out what's due today, and generates
    assignments — skipping anything already generated for that
    schedule/FY/period. A failure on one schedule is logged and does not
    stop the rest from being processed. If a section has been sent for
    Pre-Final Approval, _create_brsr_assignment raises ValueError and this
    loop simply logs and skips it — the schedule stays active but produces
    no further assignments for that locked section until it's unlocked.
    """
    today = today or timezone.localdate()
    created = []

    schedules = AssignmentSchedule.objects.filter(is_active=True).select_related(
        "plant", "section", "principle", "workflow_template"
    )
    for schedule in schedules:
        try:
            for financial_year, period_code, period_label in due_periods_for_schedule(schedule, today):
                assignment = create_assignment_from_schedule(
                    schedule, financial_year, period_code, period_label, trigger_date=today
                )
                if assignment is not None:
                    created.append(assignment)
        except Exception:
            logger.exception(
                "Failed to generate assignment(s) for schedule %s", schedule.schedule_id
            )
            continue

    return created

def build_schedule(*, created_by, plant, section, principle, financial_year,
                    assignee, reviewer, frequency, weekly_start_day=None,
                    weekly_end_day=None, selected_months=None,
                    selected_quarters=None, priority='medium', due_period_days=None, notes='',
                    name='', workflow_template=None, question_queryset=None):
    """
    Persist a reusable AssignmentSchedule carrying every bit of context a
    manually created assignment also carries (assigner/created_by, assignee,
    reviewer, priority, notes, workflow template) — so every scheduled
    assignment generated later is identical to this one except for the
    period it covers.
    """
    from .models import AssignmentSchedule
    from django.contrib.contenttypes.models import ContentType
    from django.contrib.auth import get_user_model

    User = get_user_model()
    user_ct = ContentType.objects.get_for_model(User)

    schedule = AssignmentSchedule.objects.create(
        name=name or f"{section.name} recurring assignment",
        plant=plant,
        section=section,
        principle=principle,
        financial_year=financial_year,
        workflow_template=workflow_template,
        frequency=frequency,
        weekly_start_day=weekly_start_day,
        weekly_end_day=weekly_end_day,
        selected_months=selected_months or [],
        selected_quarters=selected_quarters or [],
        priority=priority,
        due_period_days=due_period_days,
        notes=notes,
        created_by=created_by,
        assignee_content_type=user_ct,
        assignee_object_id=assignee.pk,
    )
    if reviewer is not None:
        schedule.reviewer_content_type = user_ct
        schedule.reviewer_object_id = reviewer.pk
        schedule.save(update_fields=["reviewer_content_type", "reviewer_object_id", "updated_at"])

    if question_queryset is not None:
        schedule.questions.set(question_queryset)

    return schedule


def create_assignment_and_optional_schedule(*, user, section, principle, cleaned_data, question_queryset):
    """
    Single entry point for assignment creation, used by both the "create
    assignment" API/view and (indirectly, via create_assignment_from_schedule)
    the daily Celery task.

    `data_collection_frequency` is now a MANDATORY field on
    BRSRAssignmentForm — every assignment created here always:
      1. resolves assignee/reviewer once,
      2. persists an AssignmentSchedule with them locked in,
      3. immediately generates the Assignment for *today's* current period
         through the same create_assignment_from_schedule() path the daily
         task uses.

    The schedule stays active, so run_daily_schedule_generation() picks up
    every future due period automatically — there is no separate "one-off"
    creation path anymore, and no ambiguity between manual and auto
    assignments: they are the exact same code path.

    Returns (assignment, schedule). schedule is always a real
    AssignmentSchedule instance (never None) since frequency is required.
    """
    from .views import (
        _resolve_brsr_workflow_template,
        _resolve_brsr_assignee,
        _resolve_brsr_reviewer,
        _is_section_locked_for_new_assignment,
    )

    frequency = cleaned_data.get("data_collection_frequency")
    if not frequency:
        raise ValueError("A submission frequency is required to create an assignment.")

    plant = cleaned_data["plant"]
    financial_year = cleaned_data["financial_year"]

    if _is_section_locked_for_new_assignment(user, plant, section, principle, financial_year):
        raise ValueError(
            "This section has already been sent for Pre-Final Approval for this "
            "plant and financial year. No new assignment can be created until "
            "the current one is approved or rejected."
        )

    workflow_template = _resolve_brsr_workflow_template(user=user, plant=plant)
    if not workflow_template or not workflow_template.first_stage:
        raise ValueError("No active BRSR workflow template with stages is configured for this company.")

    assignee = _resolve_brsr_assignee(
        plant, workflow_template,
        selected_assignee=cleaned_data.get("assignee"),
        current_user=user,
    )
    if assignee is None:
        raise ValueError("No eligible assignee matches the first stage of the configured BRSR workflow.")

    reviewer = _resolve_brsr_reviewer(
        plant, workflow_template,
        selected_reviewer=cleaned_data.get("reviewer"),
        current_user=user,
    )
    if cleaned_data.get("reviewer") is not None and reviewer is None:
        raise ValueError(
            "The selected reviewer is not eligible for the review stage of this "
            "workflow (role/plant mismatch). Choose a different reviewer or "
            "update the workflow template's review-stage role."
        )

    schedule = build_schedule(
        created_by=cleaned_data.get("assigner") or user,
        plant=plant,
        section=section,
        principle=principle,
        financial_year=financial_year,
        assignee=assignee,
        reviewer=reviewer,
        frequency=frequency,
        weekly_start_day=cleaned_data.get("weekly_start_day"),
        weekly_end_day=cleaned_data.get("weekly_end_day"),
        selected_months=cleaned_data.get("selected_months") or [],
        selected_quarters=cleaned_data.get("selected_quarters") or [],
        priority=cleaned_data.get("priority", "medium"),
        due_period_days=cleaned_data.get("due_period_days"),
        notes=cleaned_data.get("notes"),
        name=cleaned_data.get("schedule_name") or "",
        workflow_template=workflow_template,
        question_queryset=question_queryset,
    )

    today = timezone.localdate()
    period_financial_year, period_code, period_label = current_period_for_frequency(frequency, today)

    assignment = create_assignment_from_schedule(
        schedule, period_financial_year, period_code, period_label, trigger_date=today,
    )
    if assignment is None:
        # Only reachable if this exact schedule/period pair already existed
        # (e.g. a rapid double-submit) — not possible on first creation of
        # a brand new schedule, but guarded here for safety rather than
        # silently returning nothing.
        assignment = Assignment.objects.filter(
            schedule=schedule, financial_year=period_financial_year, period_code=period_code
        ).order_by("-created_at").first()
        if assignment is None:
            raise ValueError(
                f"An assignment already exists for {period_label or period_code} "
                f"of {period_financial_year}."
            )

    return assignment, schedule